### ISSUE TITLE
The code could not load wights from repository

### ISSUE THREAD

**Issue by Makhaon** [amirhossein-kz/HiFormer#1]
Hi! We've try to load your weights (Synapse Multi-Organ Segmentation, Learned weights) but have no success.
Code for loading:

msg = model.load_state_dict(torch.load('./orig_models/HiFormer-B.pth'))

File "E:\N_N\HiFormer-main\test.py", line 104, in <module>
    msg = model.load_state_dict(torch.load('./orig_models/HiFormer-B.pth'))
  File "C:\Users\MakUser\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for HiFormer:
 Missing key(s) in state_dict: "DLF.pyramid.swin_transformer.layers.0.blocks.0.norm1.weight", "DLF.pyramid.swin_transformer.layers.0.blocks.0.norm1.bias", "DLF.pyramid.swin_transformer.layers.0.blocks.0.attn.relative_position_bias_table", "DLF.pyramid.swin_transformer.layers.0.blocks.0.attn.relative_position_index", "DLF.pyramid.swin_transformer.layers.0.blocks.0.attn.qkv.weight", "DLF.pyramid.swin_transformer.layers.0.blocks.0.attn.qkv.bias", "DLF.pyramid.swin_transformer.layers.0.blocks.0.attn.proj.weight", 
.............
Does it possible to fix issue?

**Comment by amirhossein-kz** [comment]
Dear @Makhaon,
Thank you for your interest in our work. It is fixed now.
Thanks for your feedback.
